"""initial_schema

Revision ID: 2d64e6f050dc
Revises:
Create Date: 2026-02-14 12:22:43.465194

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2d64e6f050dc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("contact_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_code"), "customers", ["code"], unique=True)
    op.create_table(
        "locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["locations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_location_parent", "locations", ["parent_id"], unique=False)
    op.create_index(op.f("ix_locations_code"), "locations", ["code"], unique=True)
    op.create_table(
        "permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("contact_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suppliers_code"), "suppliers", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_users_active",
        "users",
        ["id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "work_centers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("uom", sa.String(length=20), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("meta_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_product_meta_data_gin", "products", ["meta_data"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    op.create_index(op.f("ix_products_customer_id"), "products", ["customer_id"], unique=False)
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_index(op.f("ix_products_supplier_id"), "products", ["supplier_id"], unique=False)
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("po_number", sa.String(length=50), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_po_status_created", "purchase_orders", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_purchase_orders_created_by"), "purchase_orders", ["created_by"], unique=False)
    op.create_index(op.f("ix_purchase_orders_po_number"), "purchase_orders", ["po_number"], unique=True)
    op.create_index(op.f("ix_purchase_orders_status"), "purchase_orders", ["status"], unique=False)
    op.create_index(op.f("ix_purchase_orders_supplier_id"), "purchase_orders", ["supplier_id"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "sales_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("so_number", sa.String(length=50), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("order_date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("delivery_date", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_so_customer_status", "sales_orders", ["customer_id", "status"], unique=False)
    op.create_index(op.f("ix_sales_orders_created_by"), "sales_orders", ["created_by"], unique=False)
    op.create_index(op.f("ix_sales_orders_customer_id"), "sales_orders", ["customer_id"], unique=False)
    op.create_index(op.f("ix_sales_orders_so_number"), "sales_orders", ["so_number"], unique=True)
    op.create_index(op.f("ix_sales_orders_status"), "sales_orders", ["status"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "boms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("bom_name", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_boms_product_id"), "boms", ["product_id"], unique=False)
    op.create_table(
        "purchase_order_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("po_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("qty_ordered", sa.Integer(), nullable=False),
        sa.Column("qty_received", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.CheckConstraint("qty_ordered > 0", name="ck_po_item_qty_ordered_positive"),
        sa.CheckConstraint("qty_received <= qty_ordered", name="ck_po_item_qty_received_not_exceed"),
        sa.CheckConstraint("qty_received >= 0", name="ck_po_item_qty_received_non_negative"),
        sa.CheckConstraint("unit_price >= 0", name="ck_po_item_unit_price_non_negative"),
        sa.ForeignKeyConstraint(["po_id"], ["purchase_orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_purchase_order_items_po_id"), "purchase_order_items", ["po_id"], unique=False)
    op.create_index(
        op.f("ix_purchase_order_items_product_id"),
        "purchase_order_items",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "sales_order_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("so_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("qty_ordered", sa.Integer(), nullable=False),
        sa.Column("qty_delivered", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.CheckConstraint("qty_delivered <= qty_ordered", name="ck_so_item_qty_delivered_not_exceed"),
        sa.CheckConstraint("qty_delivered >= 0", name="ck_so_item_qty_delivered_non_negative"),
        sa.CheckConstraint("qty_ordered > 0", name="ck_so_item_qty_ordered_positive"),
        sa.CheckConstraint("unit_price >= 0", name="ck_so_item_unit_price_non_negative"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["so_id"], ["sales_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sales_order_items_product_id"), "sales_order_items", ["product_id"], unique=False)
    op.create_index(op.f("ix_sales_order_items_so_id"), "sales_order_items", ["so_id"], unique=False)
    op.create_table(
        "stock_balances",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("current_qty", sa.Integer(), nullable=False),
        sa.Column(
            "last_updated",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_id", "location_id"),
    )
    op.create_table(
        "stock_ledgers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column("ref_type", sa.String(length=50), nullable=True),
        sa.Column("ref_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ledger_product_location", "stock_ledgers", ["product_id", "location_id"], unique=False)
    op.create_index(
        "idx_ledger_product_location_created",
        "stock_ledgers",
        ["product_id", "location_id", "created_at"],
        unique=False,
    )
    op.create_index("idx_ledger_ref", "stock_ledgers", ["ref_type", "ref_id"], unique=False)
    op.create_index(op.f("ix_stock_ledgers_created_at"), "stock_ledgers", ["created_at"], unique=False)
    op.create_index(op.f("ix_stock_ledgers_location_id"), "stock_ledgers", ["location_id"], unique=False)
    op.create_index(op.f("ix_stock_ledgers_product_id"), "stock_ledgers", ["product_id"], unique=False)
    op.create_index(
        op.f("ix_stock_ledgers_transaction_type"),
        "stock_ledgers",
        ["transaction_type"],
        unique=False,
    )
    op.create_table(
        "bom_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bom_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.String(length=50), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("work_center_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(item_type = 'material' AND product_id IS NOT NULL AND work_center_id IS NULL) OR (item_type = 'operation' AND work_center_id IS NOT NULL AND product_id IS NULL)",
            name="ck_bom_item_type_reference",
        ),
        sa.ForeignKeyConstraint(["bom_id"], ["boms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["work_center_id"], ["work_centers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bom_id", "sequence", name="uq_bom_items_sequence"),
    )
    op.create_index("idx_bom_items_bom_seq", "bom_items", ["bom_id", "sequence"], unique=False)
    op.create_index(op.f("ix_bom_items_bom_id"), "bom_items", ["bom_id"], unique=False)
    op.create_index(op.f("ix_bom_items_product_id"), "bom_items", ["product_id"], unique=False)
    op.create_index(op.f("ix_bom_items_work_center_id"), "bom_items", ["work_center_id"], unique=False)
    op.create_table(
        "production_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("bom_id", sa.Uuid(), nullable=False),
        sa.Column("so_item_id", sa.Uuid(), nullable=True),
        sa.Column("qty_planned", sa.Integer(), nullable=False),
        sa.Column("qty_produced", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("qty_planned > 0", name="ck_prod_order_qty_planned_positive"),
        sa.CheckConstraint("qty_produced >= 0", name="ck_prod_order_qty_produced_non_negative"),
        sa.ForeignKeyConstraint(["bom_id"], ["boms.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["so_item_id"], ["sales_order_items.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_prod_order_status_created", "production_orders", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_production_orders_bom_id"), "production_orders", ["bom_id"], unique=False)
    op.create_index(op.f("ix_production_orders_created_by"), "production_orders", ["created_by"], unique=False)
    op.create_index(
        op.f("ix_production_orders_order_number"),
        "production_orders",
        ["order_number"],
        unique=True,
    )
    op.create_index(op.f("ix_production_orders_product_id"), "production_orders", ["product_id"], unique=False)
    op.create_index(op.f("ix_production_orders_so_item_id"), "production_orders", ["so_item_id"], unique=False)
    op.create_index(op.f("ix_production_orders_status"), "production_orders", ["status"], unique=False)

    # =========================================================================
    # DATABASE TRIGGERS
    # =========================================================================

    # TRIGGER 1: Auto-update stock_balances setelah INSERT ke stock_ledgers
    op.execute("""
        CREATE OR REPLACE FUNCTION fn_update_stock_balance()
        RETURNS TRIGGER AS $func$
        BEGIN
            INSERT INTO stock_balances (product_id, location_id, current_qty, last_updated)
            VALUES (NEW.product_id, NEW.location_id, NEW.qty, NOW())
            ON CONFLICT (product_id, location_id)
            DO UPDATE SET
                current_qty  = stock_balances.current_qty + NEW.qty,
                last_updated = NOW();
            RETURN NEW;
        END;
        $func$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER trg_update_stock_balance
        AFTER INSERT ON stock_ledgers
        FOR EACH ROW EXECUTE FUNCTION fn_update_stock_balance();
    """)

    # TRIGGER 2: Auto-update updated_at pada UPDATE untuk semua tabel dengan TimestampMixin
    op.execute("""
        CREATE OR REPLACE FUNCTION fn_set_updated_at()
        RETURNS TRIGGER AS $func$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $func$ LANGUAGE plpgsql;
    """)

    # Terapkan ke semua tabel yang menggunakan TimestampMixin
    tables_with_timestamps = [
        "users",
        "suppliers",
        "customers",
        "products",
        "boms",
        "purchase_orders",
        "sales_orders",
        "production_orders",
    ]

    for table in tables_with_timestamps:
        op.execute(f"""
            CREATE TRIGGER trg_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # =========================================================================
    # DROP DATABASE TRIGGERS
    # =========================================================================

    # Drop triggers untuk updated_at
    tables_with_timestamps = [
        "users",
        "suppliers",
        "customers",
        "products",
        "boms",
        "purchase_orders",
        "sales_orders",
        "production_orders",
    ]

    for table in tables_with_timestamps:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table};")

    # Drop trigger untuk stock balance
    op.execute("DROP TRIGGER IF EXISTS trg_update_stock_balance ON stock_ledgers;")

    # Drop functions
    op.execute("DROP FUNCTION IF EXISTS fn_set_updated_at();")
    op.execute("DROP FUNCTION IF EXISTS fn_update_stock_balance();")

    # =========================================================================
    # DROP TABLES AND INDEXES
    # =========================================================================

    op.drop_index(op.f("ix_production_orders_status"), table_name="production_orders")
    op.drop_index(op.f("ix_production_orders_so_item_id"), table_name="production_orders")
    op.drop_index(op.f("ix_production_orders_product_id"), table_name="production_orders")
    op.drop_index(op.f("ix_production_orders_order_number"), table_name="production_orders")
    op.drop_index(op.f("ix_production_orders_created_by"), table_name="production_orders")
    op.drop_index(op.f("ix_production_orders_bom_id"), table_name="production_orders")
    op.drop_index("idx_prod_order_status_created", table_name="production_orders")
    op.drop_table("production_orders")
    op.drop_index(op.f("ix_bom_items_work_center_id"), table_name="bom_items")
    op.drop_index(op.f("ix_bom_items_product_id"), table_name="bom_items")
    op.drop_index(op.f("ix_bom_items_bom_id"), table_name="bom_items")
    op.drop_index("idx_bom_items_bom_seq", table_name="bom_items")
    op.drop_table("bom_items")
    op.drop_index(op.f("ix_stock_ledgers_transaction_type"), table_name="stock_ledgers")
    op.drop_index(op.f("ix_stock_ledgers_product_id"), table_name="stock_ledgers")
    op.drop_index(op.f("ix_stock_ledgers_location_id"), table_name="stock_ledgers")
    op.drop_index(op.f("ix_stock_ledgers_created_at"), table_name="stock_ledgers")
    op.drop_index("idx_ledger_ref", table_name="stock_ledgers")
    op.drop_index("idx_ledger_product_location_created", table_name="stock_ledgers")
    op.drop_index("idx_ledger_product_location", table_name="stock_ledgers")
    op.drop_table("stock_ledgers")
    op.drop_table("stock_balances")
    op.drop_index(op.f("ix_sales_order_items_so_id"), table_name="sales_order_items")
    op.drop_index(op.f("ix_sales_order_items_product_id"), table_name="sales_order_items")
    op.drop_table("sales_order_items")
    op.drop_index(op.f("ix_purchase_order_items_product_id"), table_name="purchase_order_items")
    op.drop_index(op.f("ix_purchase_order_items_po_id"), table_name="purchase_order_items")
    op.drop_table("purchase_order_items")
    op.drop_index(op.f("ix_boms_product_id"), table_name="boms")
    op.drop_table("boms")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_sales_orders_status"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_so_number"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_customer_id"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_created_by"), table_name="sales_orders")
    op.drop_index("idx_so_customer_status", table_name="sales_orders")
    op.drop_table("sales_orders")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_purchase_orders_supplier_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_status"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_po_number"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_created_by"), table_name="purchase_orders")
    op.drop_index("idx_po_status_created", table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(op.f("ix_products_supplier_id"), table_name="products")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_customer_id"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_index("idx_product_meta_data_gin", table_name="products", postgresql_using="gin")
    op.drop_table("products")
    op.drop_table("work_centers")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("idx_users_active", table_name="users", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_table("users")
    op.drop_index(op.f("ix_suppliers_code"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_locations_code"), table_name="locations")
    op.drop_index("idx_location_parent", table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_customers_code"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
